# GitHub Actions Workflow responsible for initializing the repository and removing  the template-specific files
# and configurations. This workflow is triggered automatically when a new template-based repository has been created.

name: Template Initialization
on:
  push:
    branches:
      - main

jobs:

  template-init:
    name: Template Initialization
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.repository.name != 'HPST-project-template'
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Cleanup project
      - name: Cleanup
        run: |
          sudo rm -rf \
            README.md \
            .github/workflows/template-init.yml

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
